# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

baseurl = "https://www.chrisfrome.com/"
defaultContentLanguage = "en"

pluralizeListTitles = true # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = false

enableEmoji = true

ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
  page = ["HTML"]
  term = ["HTML", "RSS"]

[params.seo]
  enableOpenGraph = true
  enableTwitterCards = true
  twitterUsername = "cfrome77"
  canonicalURL = "https://www.chrisfrome.com/"

[params]
  defaultFeaturedImage = "/img/homepage-share.jpg"

[related]
  # Set threshold high to require a strong topical match (tag or category)
  threshold = 50 
  toLower = true

    [[related.indices]]
        # Highest weight to ensure shared tags are prioritized
        name = "tags"
        weight = 100

    [[related.indices]]
        # Highest weight to ensure shared categories are prioritized
        name = "categories"
        weight = 100

    [[related.indices]]
        # Medium weight for linking sequential posts
        name = "series"
        weight = 50

[services]
  [services.googleAnalytics]
    ID = "G-K425XQJT21"

  [services.disqus]
    shortname = "chrisfrome"