[[main]]
name = "Blog"
url = "/posts/"
weight = 10

[[main]]
name = "Projects"
url = "/projects/"
weight = 20

[[main]]
name = "About"
url = "/about/"
weight = 30

[[main]]
name = "Resume"
url = "/resume/"
weight = 40

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
pre = "rss-square"
name = "rss"
url = "/posts/index.xml"
weight = 1

[[footer]]
name = "tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
