baseurl = "https://www.chrisfrome.com/"
title = "Chris Frome"
theme = "nix"
languageCode = "en-us"
disqusShortname = "chrisfrome"
disablePathToLower = true

[menu]
  [[menu.header]]
    identifier = "post"
    name = "posts"
    weight = 0
    url = "/post"
  [[menu.header]]
    parent = "post"
    name = "Posts"
    url = "/post"
  [[menu.header]]
    parent = "post"
    name = "categories"
    url = "/categories"
  [[menu.header]]
    parent = "post"
    name = "tags"
    url = "/tags"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "projects"
    weight = 2
    url = "/projects"

[params]
  TwitterID = "cfrome77"
  LinkedInID = "cfrome77"
  GithubID = "cfrome77"
  Name = "Chris Frome"
  HeaderUsername = "Chris"
  HeaderHostname = "chrisfrome.com"
  Email = "chris@chrisfrome.com"
  About = "Hi my name is Chris Frome. I am a Maryland based Web & Software Developer. In my free time, I enjoy community service, cooking, hiking, tabeltop RPG's, trivai, and camping/the outdoors."
  ProfilePicture = "/profile.jpg"
  GoogleAnalytics = "UA-114432266-1"


