baseurl = "http://chrisfrome.com/"
title = "Chris Frome"
theme = "nix"
languageCode = "en-us"
disqusShortname = "chrisfrome"

[menu]
  [[menu.header]]
    name = "post"
    identifier = "posts"
    weight = 0
    url = "/post"
  [[menu.main]]
    Name = "all tags"
    parent = "posts"
    URL = "/tags"
    Weight = 0
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "projects"
    weight = 2
    url = "/projects"

[params]
  GithubID = "cfrome77"
  TwitterID = "cfrome77"
  LinkedInID = "cfrome77"
  FacebookID = "cfrome77"
  Name = "Chris Frome"
  HeaderUsername = "Chris"
  HeaderHostname = "chrisfrome.com"
  Email = "chris@chrisfrome.com"
  About = "Hi I am Chris Frome. I am a software engineer from the DC metropolitan area. In my free time, I enjoy cooking, rock climbing, and camping/the outdoors."
  ProfilePicture = "/profile.jpg"
  GoogleAnalytics = "UA-114432266-1"
